### ISSUE TITLE
Websocket implementation

### ISSUE THREAD

**Issue by BRUHItsABunny** [RyanBurnsworth/NativeSocketKommunication#1]
Hey, great article and code

I was wondering how to do this exact thing 6 months ago and never knew it would be so straight forward.

I don't have much c++ experience but I am wondering how would this work with websockets rather than TCPsockets?

Also why are sockets represented as int in c++, how does that work?

**Comment by RyanBurnsworth** [comment]
Hey there, 
 Thank you for that! I really appreciate it. 
I'm not very familiar with websockets and not 100% sure, but from what I looked up, it should work similarly in Android except that you can skip the JNI and C++. It seems that you could use a WebView with JavaScript enabled, and then load the html and js files that handles the websockets into that webview.

**Comment by BRUHItsABunny** [comment]
Never heard of the webview way of doing websocket interactions, so far I have been using OkHTTP for it.
You say it would work about similarly, could you link me the information you have found?
Thanks for responding, sorry for my late response.
